-- 96 | Majlis — full setup (schema + National Day 96 content). Paste into Supabase → SQL Editor → Run.

-- 96 | Majlis party game — initial schema
-- All access goes through the Next.js API using the service role key.
-- RLS is enabled with NO public policies, so the anon key can't read answers or game state.

create table if not exists public.themes (
  id text primary key,
  name text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.categories (
  id text primary key default gen_random_uuid()::text,
  theme_id text not null references public.themes(id) on delete cascade,
  name text not null,
  description text,
  color text not null default '#22A06B',
  pattern text not null default 'star' check (pattern in ('star','lattice','arches','chevron','dots','waves')),
  mode text not null default 'normal' check (mode in ('normal','buzzer')),
  sort integer not null default 100,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.questions (
  id text primary key default gen_random_uuid()::text,
  theme_id text not null references public.themes(id) on delete cascade,
  category_id text not null references public.categories(id) on delete cascade,
  question text not null,
  answer text not null,
  type text not null default 'TEXT' check (type in ('TEXT','MULTIPLE_CHOICE','TRUE_FALSE','IMAGE','COMPLETE_PHRASE')),
  points integer not null default 100,
  image_url text,
  options jsonb,
  correct_option integer,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists questions_category_idx on public.questions(category_id);

-- One row per live game. `state` holds the whole game document (players, teams,
-- scores, phase, and a private snapshot of the questions). `version` gives
-- optimistic concurrency so simultaneous votes/buzzes never overwrite each other.
create table if not exists public.sessions (
  code text primary key,
  host_token_hash text not null,
  state jsonb not null,
  version integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Player photos and question images (small, already resized in the browser).
create table if not exists public.media (
  id text primary key,
  content_type text not null,
  data text not null,
  created_at timestamptz not null default now()
);

alter table public.themes enable row level security;
alter table public.categories enable row level security;
alter table public.questions enable row level security;
alter table public.sessions enable row level security;
alter table public.media enable row level security;

-- Generated by scripts/gen-seed-sql.ts — National Day 96 default content.
-- Safe to re-run: existing rows are updated in place.

insert into public.themes (id, name) values ('national-day-96', 'اليوم الوطني 96')
  on conflict (id) do update set name = excluded.name;

insert into public.categories (id, theme_id, name, description, color, pattern, mode, sort, active) values
  ('nd96-watani', 'national-day-96', 'وطنية 96', 'تاريخ الوطن ورموزه', '#22A06B', 'star', 'normal', 1, true),
  ('nd96-truefalse', 'national-day-96', 'صح أو خطأ', 'قرّر بسرعة', '#2F6FDE', 'lattice', 'normal', 2, true),
  ('nd96-whois', 'national-day-96', 'من هو؟', 'شخصيات سعودية', '#7E57D8', 'arches', 'normal', 3, true),
  ('nd96-complete', 'national-day-96', 'أكمل العبارة', 'النشيد والأمثال', '#D6A63A', 'chevron', 'normal', 4, true),
  ('nd96-password', 'national-day-96', 'كلمة السر', 'ثلاث تلميحات وكلمة واحدة', '#E0548A', 'dots', 'normal', 5, true),
  ('nd96-emoji', 'national-day-96', 'خمّنها بالإيموجي', 'عينك على الصورة', '#169C9C', 'waves', 'normal', 6, true),
  ('nd96-speed', 'national-day-96', 'تحدي السرعة', 'أسرع إصبع يجاوب', '#E07A3A', 'star', 'buzzer', 7, true),
  ('nd96-saudi', 'national-day-96', 'سعودي وبس', 'ثقافة وأماكن', '#2F6FDE', 'arches', 'normal', 8, true),
  ('fk-dialect', 'national-day-96', 'لهجات وعادات', 'كلامنا وسوالفنا', '#169C9C', 'lattice', 'normal', 9, true),
  ('fk-proverbs', 'national-day-96', 'أمثال وكلام سعودي', 'وش المثل؟', '#7E57D8', 'waves', 'normal', 10, true),
  ('fk-challenges', 'national-day-96', 'تحديات وأخرى', 'أول واحد يسويها', '#E0548A', 'chevron', 'buzzer', 11, true),
  ('fk-image', 'national-day-96', 'خمنها من الصورة', 'عينك على الصورة', '#2F6FDE', 'dots', 'normal', 12, false)
on conflict (id) do update set name = excluded.name, description = excluded.description, color = excluded.color,
  pattern = excluded.pattern, mode = excluded.mode, sort = excluded.sort;

insert into public.questions (id, theme_id, category_id, question, answer, type, points, image_url, options, correct_option, active) values
  ('nd96-watani-01', 'national-day-96', 'nd96-watani', 'في أي عام أُعلن توحيد المملكة العربية السعودية؟', '1932', 'MULTIPLE_CHOICE', 100, null, '["1902","1932","1945","1953"]'::jsonb, 1, true),
  ('nd96-watani-02', 'national-day-96', 'nd96-watani', 'ما الاسم الذي كانت تُعرف به البلاد قبل إعلان اسم «المملكة العربية السعودية»؟', 'مملكة الحجاز ونجد وملحقاتها', 'MULTIPLE_CHOICE', 100, null, '["سلطنة نجد","مملكة الحجاز ونجد وملحقاتها","إمارة الدرعية","المملكة العربية المتحدة"]'::jsonb, 1, true),
  ('nd96-watani-03', 'national-day-96', 'nd96-watani', 'في أي يوم من شهر سبتمبر يُحتفل باليوم الوطني السعودي؟', '23', 'MULTIPLE_CHOICE', 100, null, '["21","22","23","24"]'::jsonb, 2, true),
  ('nd96-watani-04', 'national-day-96', 'nd96-watani', 'هذا العام نحتفل باليوم الوطني السعودي رقم…', '96', 'MULTIPLE_CHOICE', 100, null, '["94","95","96","97"]'::jsonb, 2, true),
  ('nd96-watani-05', 'national-day-96', 'nd96-watani', 'من هو مؤسس المملكة العربية السعودية؟', 'الملك عبدالعزيز بن عبدالرحمن آل سعود', 'MULTIPLE_CHOICE', 100, null, '["الملك سعود","الملك عبدالعزيز بن عبدالرحمن آل سعود","الإمام محمد بن سعود","الملك فيصل"]'::jsonb, 1, true),
  ('nd96-watani-06', 'national-day-96', 'nd96-watani', 'في أي عام استردّ الملك عبدالعزيز الرياض؟', '1902', 'MULTIPLE_CHOICE', 100, null, '["1902","1912","1925","1932"]'::jsonb, 0, true),
  ('nd96-watani-07', 'national-day-96', 'nd96-watani', 'ما اسم الحصن الذي ارتبط باسترداد الرياض؟', 'قصر المصمك', 'MULTIPLE_CHOICE', 100, null, '["قصر المربع","قصر المصمك","قصر سلوى","قلعة تاروت"]'::jsonb, 1, true),
  ('nd96-watani-08', 'national-day-96', 'nd96-watani', 'كم عدد المناطق الإدارية في المملكة؟', '13', 'MULTIPLE_CHOICE', 100, null, '["11","13","15","17"]'::jsonb, 1, true),
  ('nd96-watani-09', 'national-day-96', 'nd96-watani', 'ما مكوّنات شعار المملكة العربية السعودية؟', 'نخلة وسيفان متقاطعان', 'MULTIPLE_CHOICE', 100, null, '["نخلة وسيفان متقاطعان","صقر وسيف","نخلة وهلال","سيف ونجمة"]'::jsonb, 0, true),
  ('nd96-watani-10', 'national-day-96', 'nd96-watani', 'متى يُحتفل بيوم العلم السعودي؟', '11 مارس', 'MULTIPLE_CHOICE', 100, null, '["11 مارس","22 فبراير","23 سبتمبر","1 يناير"]'::jsonb, 0, true),
  ('nd96-watani-11', 'national-day-96', 'nd96-watani', 'متى يُحتفل بيوم التأسيس؟', '22 فبراير', 'MULTIPLE_CHOICE', 100, null, '["22 فبراير","11 مارس","23 سبتمبر","15 يناير"]'::jsonb, 0, true),
  ('nd96-watani-12', 'national-day-96', 'nd96-watani', 'بأي كلمات يبدأ النشيد الوطني السعودي؟', 'سارعي للمجد والعلياء', 'MULTIPLE_CHOICE', 100, null, '["سارعي للمجد والعلياء","بلادي بلادي","موطني موطني","يا بلادي يا وطني"]'::jsonb, 0, true),
  ('nd96-watani-13', 'national-day-96', 'nd96-watani', 'في أي عام أُعلنت رؤية المملكة 2030؟', '2016', 'MULTIPLE_CHOICE', 100, null, '["2014","2016","2018","2020"]'::jsonb, 1, true),
  ('nd96-truefalse-01', 'national-day-96', 'nd96-truefalse', 'العلم السعودي لا يُنكَّس أبداً.', 'صح — لأنه يحمل كلمة التوحيد', 'TRUE_FALSE', 100, null, null, 0, true),
  ('nd96-truefalse-02', 'national-day-96', 'nd96-truefalse', 'يُحتفل باليوم الوطني السعودي في 22 فبراير.', 'خطأ — 22 فبراير يوم التأسيس، واليوم الوطني 23 سبتمبر', 'TRUE_FALSE', 100, null, null, 1, true),
  ('nd96-truefalse-03', 'national-day-96', 'nd96-truefalse', 'الربع الخالي أكبر صحراء رملية متصلة في العالم.', 'صح', 'TRUE_FALSE', 100, null, null, 0, true),
  ('nd96-truefalse-04', 'national-day-96', 'nd96-truefalse', 'أول رائد فضاء سعودي وعربي هو الأمير سلطان بن سلمان.', 'صح — عام 1985', 'TRUE_FALSE', 100, null, null, 0, true),
  ('nd96-truefalse-05', 'national-day-96', 'nd96-truefalse', 'تقع نيوم في منطقة الجوف.', 'خطأ — تقع في منطقة تبوك', 'TRUE_FALSE', 100, null, null, 1, true),
  ('nd96-truefalse-06', 'national-day-96', 'nd96-truefalse', 'ستستضيف المملكة كأس العالم 2034.', 'صح', 'TRUE_FALSE', 100, null, null, 0, true),
  ('nd96-truefalse-07', 'national-day-96', 'nd96-truefalse', 'ألوان العلم السعودي هي الأخضر والأحمر.', 'خطأ — الأخضر والأبيض', 'TRUE_FALSE', 100, null, null, 1, true),
  ('nd96-truefalse-08', 'national-day-96', 'nd96-truefalse', 'الملك سلمان بن عبدالعزيز هو سابع ملوك المملكة.', 'صح', 'TRUE_FALSE', 100, null, null, 0, true),
  ('nd96-truefalse-09', 'national-day-96', 'nd96-truefalse', 'تطل المملكة على البحر الأبيض المتوسط.', 'خطأ — تطل على البحر الأحمر والخليج العربي', 'TRUE_FALSE', 100, null, null, 1, true),
  ('nd96-truefalse-10', 'national-day-96', 'nd96-truefalse', 'الحِجر (مدائن صالح) أول موقع سعودي يُسجَّل في قائمة التراث العالمي لليونسكو.', 'صح — عام 2008', 'TRUE_FALSE', 100, null, null, 0, true),
  ('nd96-truefalse-11', 'national-day-96', 'nd96-truefalse', 'عملة المملكة هي الدينار السعودي.', 'خطأ — الريال السعودي', 'TRUE_FALSE', 100, null, null, 1, true),
  ('nd96-truefalse-12', 'national-day-96', 'nd96-truefalse', 'عاصمة المملكة العربية السعودية هي جدة.', 'خطأ — الرياض', 'TRUE_FALSE', 100, null, null, 1, true),
  ('nd96-truefalse-13', 'national-day-96', 'nd96-truefalse', 'العرضة السعودية مسجّلة في قائمة اليونسكو للتراث الثقافي غير المادي.', 'صح', 'TRUE_FALSE', 100, null, null, 0, true),
  ('nd96-whois-01', 'national-day-96', 'nd96-whois', 'وحّد المملكة وأعلن اسمها «المملكة العربية السعودية» عام 1932.', 'الملك عبدالعزيز بن عبدالرحمن آل سعود', 'TEXT', 100, null, null, null, true),
  ('nd96-whois-02', 'national-day-96', 'nd96-whois', 'أسّس الدولة السعودية الأولى في الدرعية عام 1727م.', 'الإمام محمد بن سعود', 'TEXT', 100, null, null, null, true),
  ('nd96-whois-03', 'national-day-96', 'nd96-whois', 'أول رائد فضاء عربي ومسلم، صعد إلى الفضاء عام 1985.', 'الأمير سلطان بن سلمان', 'TEXT', 100, null, null, null, true),
  ('nd96-whois-04', 'national-day-96', 'nd96-whois', 'أول رائدة فضاء سعودية، صعدت إلى محطة الفضاء الدولية عام 2023.', 'ريانة برناوي', 'TEXT', 100, null, null, null, true),
  ('nd96-whois-05', 'national-day-96', 'nd96-whois', 'رائد الفضاء السعودي الذي رافق ريانة برناوي في رحلة 2023.', 'علي القرني', 'TEXT', 100, null, null, null, true),
  ('nd96-whois-06', 'national-day-96', 'nd96-whois', 'ولي العهد، ويُعرف بأنه مهندس رؤية 2030.', 'الأمير محمد بن سلمان', 'TEXT', 100, null, null, null, true),
  ('nd96-whois-07', 'national-day-96', 'nd96-whois', 'خادم الحرمين الشريفين وملك المملكة الحالي.', 'الملك سلمان بن عبدالعزيز', 'TEXT', 100, null, null, null, true),
  ('nd96-whois-08', 'national-day-96', 'nd96-whois', 'كاتب كلمات النشيد الوطني «سارعي للمجد والعلياء».', 'إبراهيم خفاجي', 'TEXT', 100, null, null, null, true),
  ('nd96-whois-09', 'national-day-96', 'nd96-whois', 'سجّل هدف الفوز التاريخي على الأرجنتين في كأس العالم 2022.', 'سالم الدوسري', 'TEXT', 100, null, null, null, true),
  ('nd96-whois-10', 'national-day-96', 'nd96-whois', 'فنان سعودي يُلقّب بـ«فنان العرب».', 'محمد عبده', 'TEXT', 100, null, null, null, true),
  ('nd96-whois-11', 'national-day-96', 'nd96-whois', 'فنان سعودي يُلقّب بـ«صوت الأرض».', 'طلال مداح', 'TEXT', 100, null, null, null, true),
  ('nd96-whois-12', 'national-day-96', 'nd96-whois', 'شاعر وأمير يُلقّب بـ«مهندس الكلمة».', 'الأمير بدر بن عبدالمحسن', 'TEXT', 100, null, null, null, true),
  ('nd96-whois-13', 'national-day-96', 'nd96-whois', 'رمز الكرم عند العرب، وارتبط اسمه بمنطقة حائل.', 'حاتم الطائي', 'TEXT', 100, null, null, null, true),
  ('nd96-complete-01', 'national-day-96', 'nd96-complete', 'سارعي للمجد و…', 'العلياء', 'COMPLETE_PHRASE', 100, null, null, null, true),
  ('nd96-complete-02', 'national-day-96', 'nd96-complete', 'مجّدي لخالق …', 'السماء', 'COMPLETE_PHRASE', 100, null, null, null, true),
  ('nd96-complete-03', 'national-day-96', 'nd96-complete', 'وارفعي الخفّاق …', 'أخضر', 'COMPLETE_PHRASE', 100, null, null, null, true),
  ('nd96-complete-04', 'national-day-96', 'nd96-complete', 'يحمل النور …', 'المسطّر', 'COMPLETE_PHRASE', 100, null, null, null, true),
  ('nd96-complete-05', 'national-day-96', 'nd96-complete', 'ردّدي الله أكبر يا …', 'موطني', 'COMPLETE_PHRASE', 100, null, null, null, true),
  ('nd96-complete-06', 'national-day-96', 'nd96-complete', 'موطني عشتَ فخرَ …', 'المسلمين', 'COMPLETE_PHRASE', 100, null, null, null, true),
  ('nd96-complete-07', 'national-day-96', 'nd96-complete', 'الجار قبل …', 'الدار', 'COMPLETE_PHRASE', 100, null, null, null, true),
  ('nd96-complete-08', 'national-day-96', 'nd96-complete', 'من جدّ …', 'وجد', 'COMPLETE_PHRASE', 100, null, null, null, true),
  ('nd96-complete-09', 'national-day-96', 'nd96-complete', 'اللي ما يعرف الصقر …', 'يشويه', 'COMPLETE_PHRASE', 100, null, null, null, true),
  ('nd96-complete-10', 'national-day-96', 'nd96-complete', 'حبل الكذب …', 'قصير', 'COMPLETE_PHRASE', 100, null, null, null, true),
  ('nd96-complete-11', 'national-day-96', 'nd96-complete', 'على قد لحافك …', 'مد رجولك', 'COMPLETE_PHRASE', 100, null, null, null, true),
  ('nd96-complete-12', 'national-day-96', 'nd96-complete', 'العين ما تعلى على …', 'الحاجب', 'COMPLETE_PHRASE', 100, null, null, null, true),
  ('nd96-complete-13', 'national-day-96', 'nd96-complete', 'الوقت كالسيف إن لم تقطعه …', 'قطعك', 'COMPLETE_PHRASE', 100, null, null, null, true),
  ('nd96-password-01', 'national-day-96', 'nd96-password', 'أخضر • شهادة • سيف', 'العلم السعودي', 'TEXT', 100, null, null, null, true),
  ('nd96-password-02', 'national-day-96', 'nd96-password', 'نخلة • سيفان • رمز', 'شعار المملكة', 'TEXT', 100, null, null, null, true),
  ('nd96-password-03', 'national-day-96', 'nd96-password', 'دلّة • فنجال • هيل', 'القهوة السعودية', 'TEXT', 100, null, null, null, true),
  ('nd96-password-04', 'national-day-96', 'nd96-password', 'طيور جارحة • برقع • مقناص', 'الصقارة', 'TEXT', 100, null, null, null, true),
  ('nd96-password-05', 'national-day-96', 'nd96-password', 'طبول • سيوف • قصيد', 'العرضة', 'TEXT', 100, null, null, null, true),
  ('nd96-password-06', 'national-day-96', 'nd96-password', 'كثبان • رمال • أكبر صحراء رملية', 'الربع الخالي', 'TEXT', 100, null, null, null, true),
  ('nd96-password-07', 'national-day-96', 'nd96-password', 'المصمك • البطحاء • العاصمة', 'الرياض', 'TEXT', 100, null, null, null, true),
  ('nd96-password-08', 'national-day-96', 'nd96-password', 'البحر الأحمر • البلد • عروس', 'جدة', 'TEXT', 100, null, null, null, true),
  ('nd96-password-09', 'national-day-96', 'nd96-password', 'ورد • الهدا • الشفا', 'الطائف', 'TEXT', 100, null, null, null, true),
  ('nd96-password-10', 'national-day-96', 'nd96-password', 'نخيل • واحة • جبل القارة', 'الأحساء', 'TEXT', 100, null, null, null, true),
  ('nd96-password-11', 'national-day-96', 'nd96-password', 'جبل الفيل • الحِجر • آثار', 'العلا', 'TEXT', 100, null, null, null, true),
  ('nd96-password-12', 'national-day-96', 'nd96-password', 'رز • لحم • بهارات', 'الكبسة', 'TEXT', 100, null, null, null, true),
  ('nd96-password-13', 'national-day-96', 'nd96-password', '23 • سبتمبر • توحيد', 'اليوم الوطني', 'TEXT', 100, null, null, null, true),
  ('nd96-password-14', 'national-day-96', 'nd96-password', '22 • فبراير • الدرعية', 'يوم التأسيس', 'TEXT', 100, null, null, null, true),
  ('nd96-emoji-01', 'national-day-96', 'nd96-emoji', '🐪 + 🏁', 'سباق الهجن', 'TEXT', 100, null, null, null, true),
  ('nd96-emoji-02', 'national-day-96', 'nd96-emoji', '☕ + 🌴', 'القهوة والتمر', 'TEXT', 100, null, null, null, true),
  ('nd96-emoji-03', 'national-day-96', 'nd96-emoji', '🦅 + 🧤', 'الصقارة', 'TEXT', 100, null, null, null, true),
  ('nd96-emoji-04', 'national-day-96', 'nd96-emoji', '🌹 + ⛰️', 'الطائف (مدينة الورد)', 'TEXT', 100, null, null, null, true),
  ('nd96-emoji-05', 'national-day-96', 'nd96-emoji', '🌴 + ⚔️⚔️', 'شعار المملكة', 'TEXT', 100, null, null, null, true),
  ('nd96-emoji-06', 'national-day-96', 'nd96-emoji', '🐘 + 🪨', 'جبل الفيل في العلا', 'TEXT', 100, null, null, null, true),
  ('nd96-emoji-07', 'national-day-96', 'nd96-emoji', '🚀 + 👩‍🚀 + 🇸🇦', 'ريانة برناوي', 'TEXT', 100, null, null, null, true),
  ('nd96-emoji-08', 'national-day-96', 'nd96-emoji', '⚽ 🇸🇦 2 – 1 🇦🇷', 'فوز السعودية على الأرجنتين في كأس العالم 2022', 'TEXT', 100, null, null, null, true),
  ('nd96-emoji-09', 'national-day-96', 'nd96-emoji', '🛢️ + 7️⃣', 'بئر الدمام رقم 7 (بئر الخير)', 'TEXT', 100, null, null, null, true),
  ('nd96-emoji-10', 'national-day-96', 'nd96-emoji', '🚇 + 🏙️', 'مترو الرياض', 'TEXT', 100, null, null, null, true),
  ('nd96-emoji-11', 'national-day-96', 'nd96-emoji', '🌊 + 👰', 'جدة (عروس البحر الأحمر)', 'TEXT', 100, null, null, null, true),
  ('nd96-emoji-12', 'national-day-96', 'nd96-emoji', '🏜️ + ¼', 'الربع الخالي', 'TEXT', 100, null, null, null, true),
  ('nd96-emoji-13', 'national-day-96', 'nd96-emoji', '🥁 + ⚔️ + 🎶', 'العرضة', 'TEXT', 100, null, null, null, true),
  ('nd96-speed-01', 'national-day-96', 'nd96-speed', 'ما عاصمة المملكة العربية السعودية؟', 'الرياض', 'TEXT', 100, null, null, null, true),
  ('nd96-speed-02', 'national-day-96', 'nd96-speed', 'ما عملة المملكة؟', 'الريال السعودي', 'TEXT', 100, null, null, null, true),
  ('nd96-speed-03', 'national-day-96', 'nd96-speed', 'كم عدد المناطق الإدارية في المملكة؟', '13', 'TEXT', 100, null, null, null, true),
  ('nd96-speed-04', 'national-day-96', 'nd96-speed', 'ما البحر الذي يطل عليه غرب المملكة؟', 'البحر الأحمر', 'TEXT', 100, null, null, null, true),
  ('nd96-speed-05', 'national-day-96', 'nd96-speed', 'ما المسطح المائي على الساحل الشرقي للمملكة؟', 'الخليج العربي', 'TEXT', 100, null, null, null, true),
  ('nd96-speed-06', 'national-day-96', 'nd96-speed', 'في أي منطقة تقع نيوم؟', 'تبوك', 'TEXT', 100, null, null, null, true),
  ('nd96-speed-07', 'national-day-96', 'nd96-speed', 'في أي منطقة تقع جزر فرسان؟', 'جازان', 'TEXT', 100, null, null, null, true),
  ('nd96-speed-08', 'national-day-96', 'nd96-speed', 'أي مدينة تُلقّب بمدينة الورد؟', 'الطائف', 'TEXT', 100, null, null, null, true),
  ('nd96-speed-09', 'national-day-96', 'nd96-speed', 'جسر الملك فهد يربط المملكة بأي دولة؟', 'البحرين', 'TEXT', 100, null, null, null, true),
  ('nd96-speed-10', 'national-day-96', 'nd96-speed', 'أي مدينة ستستضيف إكسبو 2030؟', 'الرياض', 'TEXT', 100, null, null, null, true),
  ('nd96-speed-11', 'national-day-96', 'nd96-speed', 'كم عدد ملوك المملكة حتى اليوم؟', 'سبعة', 'TEXT', 100, null, null, null, true),
  ('nd96-speed-12', 'national-day-96', 'nd96-speed', 'في أي شهر ميلادي يُحتفل باليوم الوطني؟', 'سبتمبر', 'TEXT', 100, null, null, null, true),
  ('nd96-speed-13', 'national-day-96', 'nd96-speed', 'ما لونا العلم السعودي؟', 'الأخضر والأبيض', 'TEXT', 100, null, null, null, true),
  ('nd96-saudi-01', 'national-day-96', 'nd96-saudi', 'أي عام سُمّي «عام القهوة السعودية»؟', '2022', 'MULTIPLE_CHOICE', 100, null, '["2020","2021","2022","2024"]'::jsonb, 2, true),
  ('nd96-saudi-02', 'national-day-96', 'nd96-saudi', 'عام 2024 سُمّي في المملكة:', 'عام الإبل', 'MULTIPLE_CHOICE', 100, null, '["عام الإبل","عام الخيل","عام الصقور","عام النخلة"]'::jsonb, 0, true),
  ('nd96-saudi-03', 'national-day-96', 'nd96-saudi', 'في أي منطقة تقع محافظة العلا؟', 'المدينة المنورة', 'MULTIPLE_CHOICE', 100, null, '["المدينة المنورة","تبوك","حائل","الجوف"]'::jsonb, 0, true),
  ('nd96-saudi-04', 'national-day-96', 'nd96-saudi', 'أين يقع حي الطريف التاريخي المسجّل في اليونسكو؟', 'الدرعية', 'MULTIPLE_CHOICE', 100, null, '["الدرعية","العلا","جدة","الأحساء"]'::jsonb, 0, true),
  ('nd96-saudi-05', 'national-day-96', 'nd96-saudi', 'ما النسيج البدوي التقليدي المسجّل في قائمة اليونسكو؟', 'السدو', 'MULTIPLE_CHOICE', 100, null, '["السدو","البشت","الزري","الشماغ"]'::jsonb, 0, true),
  ('nd96-saudi-06', 'national-day-96', 'nd96-saudi', 'فن تزيين جدران البيوت في عسير المسجّل في اليونسكو هو:', 'القط العسيري', 'MULTIPLE_CHOICE', 100, null, '["القط العسيري","السدو","الخط الكوفي","الأرابيسك"]'::jsonb, 0, true),
  ('nd96-saudi-07', 'national-day-96', 'nd96-saudi', 'أي مدينة تُسمّى «عروس البحر الأحمر»؟', 'جدة', 'MULTIPLE_CHOICE', 100, null, '["جدة","ينبع","الوجه","جازان"]'::jsonb, 0, true),
  ('nd96-saudi-08', 'national-day-96', 'nd96-saudi', 'ما أول بئر نفط تجاري في المملكة؟', 'بئر الدمام رقم 7', 'MULTIPLE_CHOICE', 100, null, '["بئر الدمام رقم 7","بئر الغوار 1","بئر أبقيق 3","بئر الظهران 12"]'::jsonb, 0, true),
  ('nd96-saudi-09', 'national-day-96', 'nd96-saudi', 'في أي عام اكتُشف النفط تجارياً في المملكة؟', '1938', 'MULTIPLE_CHOICE', 100, null, '["1932","1938","1945","1950"]'::jsonb, 1, true),
  ('nd96-saudi-10', 'national-day-96', 'nd96-saudi', 'في أي مدينة يقع قصر المصمك؟', 'الرياض', 'MULTIPLE_CHOICE', 100, null, '["الرياض","حائل","جدة","بريدة"]'::jsonb, 0, true),
  ('nd96-saudi-11', 'national-day-96', 'nd96-saudi', 'ما اسم القطار السريع الذي يربط مكة المكرمة بالمدينة المنورة؟', 'قطار الحرمين', 'MULTIPLE_CHOICE', 100, null, '["قطار الحرمين","قطار الشمال","قطار الرياض","قطار الخليج"]'::jsonb, 0, true),
  ('nd96-saudi-12', 'national-day-96', 'nd96-saudi', 'أي واحة سعودية تُعدّ من أكبر واحات النخيل في العالم؟', 'الأحساء', 'MULTIPLE_CHOICE', 100, null, '["الأحساء","القطيف","تيماء","خيبر"]'::jsonb, 0, true),
  ('nd96-saudi-13', 'national-day-96', 'nd96-saudi', 'ما اسم أكبر صحراء رملية في المملكة؟', 'الربع الخالي', 'MULTIPLE_CHOICE', 100, null, '["الربع الخالي","النفود الكبير","الدهناء","الجافورة"]'::jsonb, 0, true),
  ('fk-watani-01', 'national-day-96', 'nd96-watani', 'ما هي أكبر مدينة في المملكة العربية السعودية؟', 'الرياض', 'TEXT', 100, null, null, null, true),
  ('fk-watani-02', 'national-day-96', 'nd96-watani', 'متى يكون تاريخ اليوم الوطني السعودي؟', '23 سبتمبر', 'TEXT', 100, null, null, null, true),
  ('fk-watani-03', 'national-day-96', 'nd96-watani', 'ما هو شعار اليوم الوطني السعودي 96؟', 'عزنا بطبعنا', 'TEXT', 100, null, null, null, true),
  ('fk-watani-04', 'national-day-96', 'nd96-watani', 'ما الحي التاريخي الشهير في الدرعية والمسجل في اليونسكو؟', 'حي الطريف', 'MULTIPLE_CHOICE', 100, null, '["حي المنيف","حي الطريف","حي الخفيف"]'::jsonb, 1, true),
  ('fk-watani-05', 'national-day-96', 'nd96-watani', 'فوق هام السحب…', 'وإن كنت ثرى', 'COMPLETE_PHRASE', 100, null, null, null, true),
  ('fk-watani-06', 'national-day-96', 'nd96-watani', 'ارفع راسك أنت…', 'سعودي', 'COMPLETE_PHRASE', 100, null, null, null, true),
  ('fk-watani-07', 'national-day-96', 'nd96-watani', 'لدى السعوديين همة مثل هذا الجبل، ما اسم الجبل؟', 'جبل طويق', 'TEXT', 100, null, null, null, true),
  ('fk-watani-08', 'national-day-96', 'nd96-watani', 'قامت هذه الدولة على أساس أنها دولة التوحيد ودعوة لدين الله ورسوله. من أكون؟', 'المملكة العربية السعودية', 'TEXT', 100, null, null, null, true),
  ('fk-dialect-01', 'national-day-96', 'fk-dialect', 'إذا قال لك أحد «اهجد»، وش يقصد؟', 'اهدأ', 'MULTIPLE_CHOICE', 100, null, '["اهجم","اهدأ","اهرب"]'::jsonb, 1, true),
  ('fk-dialect-02', 'national-day-96', 'fk-dialect', 'وش ترد على جملة «هذا ما هو قدرك»؟', 'من طيب أصلك', 'MULTIPLE_CHOICE', 100, null, '["من طيب أصلك","عاش من شافك","الله يحييك ويبقيك"]'::jsonb, 0, true),
  ('fk-heritage-01', 'national-day-96', 'nd96-saudi', 'منطقة مشهورة برقصة «الدحة»؟', 'الجوف', 'MULTIPLE_CHOICE', 100, null, '["الرياض","الجوف","مكة"]'::jsonb, 1, true),
  ('fk-heritage-02', 'national-day-96', 'nd96-saudi', 'طبق شعبي من القمح يُطبخ حتى يصبح قوامه متماسك، وش هو؟', 'الجريش', 'MULTIPLE_CHOICE', 100, null, '["القرصان","الجريش","المرقوق"]'::jsonb, 1, true),
  ('fk-image-01', 'national-day-96', 'fk-image', 'خمّن المدينة من الصورة', 'جدة (الجدة ↔ مدينة جدة)', 'IMAGE', 100, null, null, null, false),
  ('fk-proverbs-01', 'national-day-96', 'fk-proverbs', 'ما المثل السعودي الذي يُضرب لمن ينتقد شيئاً أو يقلل من قيمته لأنه يجهل قيمته الحقيقية؟', 'اللي ما يعرف الصقر يشويه', 'TEXT', 100, null, null, null, true),
  ('fk-proverbs-02', 'national-day-96', 'fk-proverbs', 'ما المثل الذي يُضرب في أن الإنسان يحكم على الآخرين غالباً من خلال أخلاقه وصفاته الشخصية؟', 'كل يرى الناس بعين طبعه', 'TEXT', 100, null, null, null, true),
  ('fk-password-01', 'national-day-96', 'nd96-password', 'كلمة السر 🤫 — المضيف يُري الكلمة للاعب واحد فقط، وهو يلمّح لفريقه بدون ما يقولها', 'قلم أخضر', 'TEXT', 100, null, null, null, true),
  ('fk-password-02', 'national-day-96', 'nd96-password', 'كلمة السر 🤫 — المضيف يُري الكلمة للاعب واحد فقط، وهو يلمّح لفريقه بدون ما يقولها', 'ملعقة', 'TEXT', 100, null, null, null, true),
  ('fk-password-03', 'national-day-96', 'nd96-password', 'كلمة السر 🤫 — المضيف يُري الكلمة للاعب واحد فقط، وهو يلمّح لفريقه بدون ما يقولها', 'قلم أخضر وكوب أخضر', 'TEXT', 100, null, null, null, true),
  ('fk-password-04', 'national-day-96', 'nd96-password', 'كلمة السر 🤫 — المضيف يُري الكلمة للاعب واحد فقط، وهو يلمّح لفريقه بدون ما يقولها', 'سبيكة', 'TEXT', 100, null, null, null, true),
  ('fk-wordsearch-01', 'national-day-96', 'fk-image', 'ابحث عن الكلمة في الصورة', 'السعودية', 'IMAGE', 100, null, null, null, false),
  ('fk-wordsearch-02', 'national-day-96', 'fk-image', 'ابحث عن الكلمة في الصورة', 'ملك', 'IMAGE', 100, null, null, null, false),
  ('fk-challenge-01', 'national-day-96', 'fk-challenges', 'أول شخص يكتب ويصوّر 📸', 'أول من ينجز التحدي ويُريه للمضيف', 'TEXT', 100, null, null, null, true),
  ('fk-challenge-02', 'national-day-96', 'fk-challenges', 'أول شخص يصوّر 📸', 'أول من ينجز التحدي ويُريه للمضيف', 'TEXT', 100, null, null, null, true),
  ('fk-challenge-03', 'national-day-96', 'fk-challenges', 'أول شخص يصوّر علم السعودية 🇸🇦', 'أول من ينجز التحدي ويُريه للمضيف', 'TEXT', 100, null, null, null, true),
  ('fk-challenge-04', 'national-day-96', 'fk-challenges', 'أول شخص يصوّر قلم أخضر', 'أول من ينجز التحدي ويُريه للمضيف', 'TEXT', 100, null, null, null, true),
  ('fk-challenge-05', 'national-day-96', 'fk-challenges', 'أول شخص يصوّر ملعقة', 'أول من ينجز التحدي ويُريه للمضيف', 'TEXT', 100, null, null, null, true),
  ('fk-challenge-06', 'national-day-96', 'fk-challenges', 'أول شخص يصوّر قلم أخضر وكوب أخضر', 'أول من ينجز التحدي ويُريه للمضيف', 'TEXT', 100, null, null, null, true),
  ('fk-challenge-07', 'national-day-96', 'fk-challenges', 'أول شخص يحط خلفية جوال وطنية', 'أول من ينجز التحدي ويُريه للمضيف', 'TEXT', 100, null, null, null, true)
on conflict (id) do update set question = excluded.question, answer = excluded.answer, type = excluded.type,
  points = excluded.points, options = excluded.options, correct_option = excluded.correct_option, updated_at = now();

-- V1.7: question difficulty (easy / medium / hard). NULL = treated as medium.
alter table public.questions add column if not exists difficulty text;
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'questions_difficulty_check') then
    alter table public.questions add constraint questions_difficulty_check check (difficulty is null or difficulty in ('easy','medium','hard'));
  end if;
end $$;
create index if not exists questions_category_difficulty_idx on public.questions(category_id, difficulty);

update public.questions set difficulty = 'easy' where difficulty is null and id in ('fk-challenge-01', 'fk-challenge-02', 'fk-challenge-03', 'fk-challenge-05', 'fk-heritage-02', 'fk-password-02', 'fk-watani-01', 'fk-watani-02', 'fk-watani-06', 'nd96-complete-01', 'nd96-complete-07', 'nd96-complete-08', 'nd96-complete-10', 'nd96-complete-11', 'nd96-complete-12', 'nd96-emoji-01', 'nd96-emoji-03', 'nd96-emoji-08', 'nd96-emoji-13', 'nd96-password-01', 'nd96-password-03', 'nd96-password-05', 'nd96-password-06', 'nd96-password-07', 'nd96-password-08', 'nd96-password-12', 'nd96-password-13', 'nd96-saudi-07', 'nd96-saudi-10', 'nd96-saudi-11', 'nd96-saudi-13', 'nd96-speed-01', 'nd96-speed-02', 'nd96-speed-04', 'nd96-speed-05', 'nd96-speed-09', 'nd96-speed-12', 'nd96-speed-13', 'nd96-truefalse-02', 'nd96-truefalse-04', 'nd96-truefalse-06', 'nd96-truefalse-07', 'nd96-truefalse-09', 'nd96-truefalse-11', 'nd96-truefalse-12', 'nd96-watani-03', 'nd96-watani-04', 'nd96-watani-05', 'nd96-watani-09', 'nd96-watani-12', 'nd96-whois-01', 'nd96-whois-03', 'nd96-whois-06', 'nd96-whois-07', 'nd96-whois-09', 'nd96-whois-10');
update public.questions set difficulty = 'medium' where difficulty is null and id in ('fk-challenge-04', 'fk-challenge-07', 'fk-dialect-01', 'fk-dialect-02', 'fk-password-01', 'fk-proverbs-01', 'fk-watani-03', 'fk-watani-04', 'fk-watani-05', 'fk-watani-07', 'fk-watani-08', 'nd96-complete-02', 'nd96-complete-03', 'nd96-complete-05', 'nd96-complete-09', 'nd96-complete-13', 'nd96-emoji-02', 'nd96-emoji-04', 'nd96-emoji-05', 'nd96-emoji-06', 'nd96-emoji-07', 'nd96-emoji-10', 'nd96-emoji-11', 'nd96-password-02', 'nd96-password-04', 'nd96-password-09', 'nd96-password-11', 'nd96-password-14', 'nd96-saudi-02', 'nd96-saudi-04', 'nd96-saudi-05', 'nd96-saudi-08', 'nd96-saudi-12', 'nd96-speed-03', 'nd96-speed-06', 'nd96-speed-08', 'nd96-speed-10', 'nd96-truefalse-01', 'nd96-truefalse-03', 'nd96-truefalse-05', 'nd96-watani-01', 'nd96-watani-07', 'nd96-watani-08', 'nd96-watani-10', 'nd96-watani-11', 'nd96-watani-13', 'nd96-whois-02', 'nd96-whois-04', 'nd96-whois-11', 'nd96-whois-12', 'nd96-whois-13');
update public.questions set difficulty = 'hard' where difficulty is null and id in ('fk-challenge-06', 'fk-heritage-01', 'fk-password-03', 'fk-password-04', 'fk-proverbs-02', 'nd96-complete-04', 'nd96-complete-06', 'nd96-emoji-09', 'nd96-emoji-12', 'nd96-password-10', 'nd96-saudi-01', 'nd96-saudi-03', 'nd96-saudi-06', 'nd96-saudi-09', 'nd96-speed-07', 'nd96-speed-11', 'nd96-truefalse-08', 'nd96-truefalse-10', 'nd96-truefalse-13', 'nd96-watani-02', 'nd96-watani-06', 'nd96-whois-05', 'nd96-whois-08');
-- anything else (host-created questions) stays NULL and is treated as «متوسط» by the game.
